services:
  mariadb:
    build: requirements/mariadb/.
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/mariaDB_volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception_network
    secrets:
      - wp_admin_pw
      - db_root_pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  nginx:
    restart: unless-stopped
    build: requirements/nginx/.
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - ${VOLUME_PATH}/wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress/.
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 12s
    volumes:
      - ${VOLUME_PATH}/wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    secrets:
      - wp_admin_pw
      - wp_user_pw

# volumes:
#   wordpress_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/wordpress_volume
#       type: none
#   mariaDB_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/mariaDB_volume
#       type: none

networks:
  inception_network:

secrets:
  wp_admin_pw:
    file: ../secrets/wp_admin_password.txt
  wp_user_pw:
    file: ../secrets/wp_user_password.txt
  db_root_pw:
    file: ../secrets/db_root_password.txt


