services:

  mariadb:
    container_name: "mariadb"
    build: requirements/mariadb/.
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/mariaDB_volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - inception_network
    secrets:
      - wp_admin_pw
      - db_root_pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  nginx:
    container_name: "nginx"
    restart: unless-stopped
    build: requirements/nginx/.
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443
    volumes:
      - ${VOLUME_PATH}/wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network

  wordpress:
    container_name: "wordpress"
    build: requirements/wordpress/.
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - ${VOLUME_PATH}/wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    secrets:
      - wp_admin_pw
      - wp_user_pw

  redis:
    container_name: "redis"
    build: requirements/bonus/redis/.
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 30s      # Check every 30 seconds
      retries: 3         # Retry 3 times before marking as unhealthy
      start_period: 10s  # Allow 10 seconds for the container to start
      timeout: 5s        # Timeout after 5 seconds if no response
    networks:
      - inception_network
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    build: requirements/bonus/adminer/.
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network

  website:
    container_name: website
    build: requirements/bonus/website/.
    restart: unless-stopped
    ports:
      - 6969:6969
    networks:
      - inception_network

  ftp-server:
    container_name: ftp-server
    build: requirements/bonus/ftp/.
    restart: unless-stopped
    volumes:
      -  ${VOLUME_PATH}/ftp_volume:/home/ftpuser
    ports:
      - 21:21
    networks:
      - inception_network
    secrets:
      - ftp_user_pw
    env_file:
      - .env

  portainer:
    container_name: portainer
    build: requirements/bonus/portainer/.
    restart: unless-stopped
    volumes:
      -  ${VOLUME_PATH}/portainer_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - inception_network
    secrets:
      - port_admin_pw


# volumes:
#   wordpress_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/wordpress_volume
#       type: none
#   mariaDB_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/mariaDB_volume
#       type: none
#   ftp_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/ftp_volume
#       type: none
#    portainer_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       device: ${VOLUME_PATH}/portainer_volume
#       type: none
networks:
  inception_network:

secrets:
  wp_admin_pw:
    file: ../secrets/wp_admin_password.txt
  wp_user_pw:
    file: ../secrets/wp_user_password.txt
  db_root_pw:
    file: ../secrets/db_root_password.txt
  ftp_user_pw:
    file: ../secrets/ftp_user_password.txt
  port_admin_pw:
    file: ../secrets/portainer_admin_password.txt

