version: "2"

services:
  mariadb:
    build: requirements/mariadb/.
    volumes:
      - mariaDB_volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception_network


  nginx:
    build: requirements/nginx/.
    ports:
      - "80:80"
    volumes:
      - vol_nginx_wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress/.
    volumes:
      - vol_nginx_wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network

volumes:
  vol_nginx_wordpress:
    driver: local
    driver_opts:
      o: bind
      device: /Users/pstrohal/source/core/inception/srcs/volumes/wordpress_volume
      type: none
  mariaDB_volume:
    driver: local
    driver_opts:
      o: bind
      device: /Users/pstrohal/source/core/inception/srcs/volumes/mariaDB_volume
      type: none

networks:
  inception_network:

secrets:
  wp_admin_pw:
    file: ./secrets/wp_admin_password.txt
  db_root_pw:
    file: ./secrets/db_root_password.txt
  wp_admin:
    file: ./secrets/

